CREATE TABLE IF NOT EXISTS Xbox.registeredUsers
(
	id	INT NOT NULL AUTO_INCREMENT,
	username	VARCHAR(24) NOT NULL,
	password 	VARCHAR(24) NOT NULL,
	joinedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(id)
);